module.exports = [
  {
    name: "Barbell Bench Press",
    description:
      "Muscles Targeted: Pectoralis major (chest), anterior deltoids (front shoulders), triceps",
    intensity: 2,
    video: null,
    muscles: ["chest", "front-deltoids", "triceps"],
    equipment: ["Barbell"],
  },
  {
    name: "Incline Bench Press",
    description:
      "Muscles Targeted: Upper chest (clavicular head of pectoralis major), anterior deltoids, triceps",
    intensity: 2,
    video: null,
    muscles: ["chest", "front-deltoids", "triceps"],
    equipment: ["Barbell"],
  },
  {
    name: "Dumbbell Flyes",
    description:
      "Muscles Targeted: Pectoralis major, anterior deltoids, serratus anterior",
    intensity: 2,
    video: null,
    muscles: ["chest", "front-deltoids"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Push-ups",
    description:
      "Muscles Targeted: Pectoralis major, anterior deltoids, triceps, serratus anterior",
    intensity: 1,
    video: null,
    muscles: ["chest", "front-deltoids", "triceps"],
    equipment: [],
  },
  {
    name: "Cable Chest Press",
    description:
      "Muscles Targeted: Pectoralis major, anterior deltoids, triceps",
    intensity: 2,
    video: null,
    muscles: ["chest", "front-deltoids", "triceps"],
    equipment: ["Cable"],
  },
  {
    name: "Chest Dips",
    description:
      "Muscles Targeted: Pectoralis major, anterior deltoids, triceps, serratus anterior",
    intensity: 2,
    video: null,
    muscles: ["chest", "front-deltoids", "triceps"],
    equipment: [],
  },
  {
    name: "Deadlift",
    description:
      "Muscles Targeted: Erector spine (lower back), latissimus dorsi (lats), trapezius, rhomboids, glutes, hamstrings",
    intensity: 3,
    video: null,
    muscles: ["lower-back", "upper-back", "hamstring", "gluteal"],
    equipment: ["Barbell"],
  },
  {
    name: "Pull-ups/Chin-ups",
    description:
      "Muscles Targeted: Latissimus dorsi, biceps, rear deltoids, upper back (trapezius and rhomboids)",
    intensity: 3,
    video: null,
    muscles: ["upper-back", "biceps", "back-deltoids"],
    equipment: [],
  },
  {
    name: "Bent-over Rows",
    description:
      "Muscles Targeted: Latissimus dorsi, rhomboids, lower and middle trapezius, rear deltoids, biceps",
    intensity: 2,
    video: null,
    muscles: ["upper-back", "biceps", "back-deltoids"],
    equipment: ["Barbell", "Dumbbells"],
  },
  {
    name: "T-Bar Rows",
    description:
      "Muscles Targeted: Latissimus dorsi, rhomboids, rear deltoids, lower and middle trapezius, biceps",
    intensity: 2,
    video: null,
    muscles: ["upper-back", "biceps", "back-deltoids"],
    equipment: ["Barbell"],
  },
  {
    name: "Lat Pulldowns",
    description:
      "Muscles Targeted: Latissimus dorsi, biceps, rear deltoids, upper back (trapezius and rhomboids)",
    intensity: 2,
    video: null,
    muscles: ["upper-back", "biceps", "back-deltoids"],
    equipment: ["Cable"],
  },
  {
    name: "Seated Cable Rows",
    description:
      "Muscles Targeted: Latissimus dorsi, rhomboids, rear deltoids, lower and middle trapezius, biceps",
    intensity: 2,
    video: null,
    muscles: ["upper-back", "biceps", "back-deltoids"],
    equipment: ["Cable"],
  },
  {
    name: "Squats",
    description: "Muscles Targeted: Quadriceps, hamstrings, glutes, calves",
    intensity: 3,
    video: null,
    muscles: ["quadriceps", "hamstring", "gluteal", "calves"],
    equipment: ["Barbell"],
  },
  {
    name: "Lunges",
    description: "Muscles Targeted: Quadriceps, hamstrings, glutes, calves",
    intensity: 2,
    video: null,
    muscles: ["quadriceps", "hamstring", "gluteal", "calves"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Leg Press",
    description: "Muscles Targeted: Quadriceps, hamstrings, glutes, calves",
    intensity: 2,
    video: null,
    muscles: ["quadriceps", "hamstring", "gluteal", "calves"],
    equipment: ["Machine"],
  },
  {
    name: "Romanian Deadlifts",
    description: "Muscles Targeted: Hamstrings, glutes, lower back",
    intensity: 3,
    video: null,
    muscles: ["hamstring", "gluteal", "lower-back"],
    equipment: ["Barbell"],
  },
  {
    name: "Leg Curls",
    description: "Muscles Targeted: Hamstrings",
    intensity: 2,
    video: null,
    muscles: ["hamstring"],
    equipment: ["Machine"],
  },
  {
    name: "Calf Raises",
    description: "Muscles Targeted: Gastrocnemius, soleus",
    intensity: 1,
    video: null,
    muscles: ["calves"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Overhead Press",
    description: "Muscles Targeted: Deltoids (shoulders), triceps",
    intensity: 3,
    video: null,
    muscles: ["front-deltoids", "triceps"],
    equipment: ["Barbell", "Dumbbells"],
  },
  {
    name: "Lateral Raises",
    description: "Muscles Targeted: Lateral deltoids",
    intensity: 2,
    video: null,
    muscles: ["front-deltoids"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Front Raises",
    description: "Muscles Targeted: Anterior deltoids",
    intensity: 2,
    video: null,
    muscles: ["front-deltoids"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Upright Rows",
    description: "Muscles Targeted: Deltoids, traps, biceps",
    intensity: 2,
    video: null,
    muscles: ["front-deltoids", "biceps", "trapezius"],
    equipment: ["Barbell"],
  },
  {
    name: "Arnold Press",
    description: "Muscles Targeted: Deltoids, triceps",
    intensity: 3,
    video: null,
    muscles: ["front-deltoids", "triceps"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Face Pulls",
    description:
      "Muscles Targeted: Rear deltoids, rhomboids, traps, external rotators of the shoulder",
    intensity: 2,
    video: null,
    muscles: ["back-deltoids", "upper-back", "trapezius"],
    equipment: ["Cable"],
  },
  {
    name: "Barbell or Dumbbell Bicep Curl",
    description: "Muscles Targeted: Biceps brachii",
    intensity: 2,
    video: null,
    muscles: ["biceps"],
    equipment: ["Barbell", "Dumbbells"],
  },
  {
    name: "Hammer Curls",
    description:
      "Muscles Targeted: Biceps brachii, brachialis, brachioradialis",
    intensity: 2,
    video: null,
    muscles: ["biceps"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Preacher Curls",
    description: "Muscles Targeted: Biceps brachii",
    intensity: 2,
    video: null,
    muscles: ["biceps"],
    equipment: ["Barbell", "Dumbbells"],
  },
  {
    name: "Concentration Curls",
    description: "Muscles Targeted: Biceps brachii",
    intensity: 2,
    video: null,
    muscles: ["biceps"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Tricep Dips",
    description: "Muscles Targeted: Triceps, chest, shoulders",
    intensity: 3,
    video: null,
    muscles: ["triceps", "chest", "front-deltoids"],
    equipment: [],
  },
  {
    name: "Skullcrushers",
    description: "Muscles Targeted: Triceps",
    intensity: 3,
    video: null,
    muscles: ["triceps"],
    equipment: ["Barbell"],
  },
  {
    name: "Tricep Kickbacks",
    description: "Muscles Targeted: Triceps",
    intensity: 2,
    video: null,
    muscles: ["triceps"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Cable Tricep Pushdowns",
    description: "Muscles Targeted: Triceps",
    intensity: 2,
    video: null,
    muscles: ["triceps"],
    equipment: ["Cable"],
  },
  {
    name: "Overhead Tricep Extension",
    description: "Muscles Targeted: Triceps",
    intensity: 2,
    video: null,
    muscles: ["triceps"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Plank",
    description:
      "Muscles Targeted: Rectus abdominis, transverse abdominis, obliques, hip flexors",
    intensity: 2,
    video: null,
    muscles: ["abs"],
    equipment: [],
  },
  {
    name: "Russian Twists",
    description: "Muscles Targeted: Obliques, rectus abdominis",
    intensity: 2,
    video: null,
    muscles: ["obliques", "abs"],
    equipment: ["Dumbbells"],
  },
  {
    name: "Bicycle Crunches",
    description: "Muscles Targeted: Rectus abdominis, obliques",
    intensity: 2,
    video: null,
    muscles: ["abs", "obliques"],
    equipment: [],
  },
  {
    name: "Leg Raises",
    description: "Muscles Targeted: Lower abdominals, hip flexors",
    intensity: 2,
    video: null,
    muscles: ["abs"],
    equipment: [],
  },
  {
    name: "Mountain Climbers",
    description: "Muscles Targeted: Full core, shoulders, hip flexors",
    intensity: 3,
    video: null,
    muscles: ["abs", "front-deltoids"],
    equipment: [],
  },
  {
    name: "Woodchoppers",
    description:
      "Muscles Targeted: Obliques, rectus abdominis, transverse abdominis",
    intensity: 3,
    video: null,
    muscles: ["obliques", "abs"],
    equipment: ["Dumbbells"],
  },
];
